//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompanying research process in the classroom and in the lab.
        /// </summary>
        public static string Accompanying {
            get {
                return ResourceManager.GetString("Accompanying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities Of The Student.
        /// </summary>
        public static string ActivitiesOfStudent {
            get {
                return ResourceManager.GetString("ActivitiesOfStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Name.
        /// </summary>
        public static string ActivityName {
            get {
                return ResourceManager.GetString("ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Name Required.
        /// </summary>
        public static string ActivityNameRequired {
            get {
                return ResourceManager.GetString("ActivityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add instructions for measures (For each parameter).
        /// </summary>
        public static string AddInstructionsForMeasures {
            get {
                return ResourceManager.GetString("AddInstructionsForMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add measure.
        /// </summary>
        public static string AddMeasure {
            get {
                return ResourceManager.GetString("AddMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add measures to set.
        /// </summary>
        public static string AddMeasuresToSet {
            get {
                return ResourceManager.GetString("AddMeasuresToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parameter to measure.
        /// </summary>
        public static string AddParameterToMeasure {
            get {
                return ResourceManager.GetString("AddParameterToMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Step.
        /// </summary>
        public static string AddStep {
            get {
                return ResourceManager.GetString("AddStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the students got their permissions.
        /// </summary>
        public static string AllOfTheStudentsGotTheirPermissions {
            get {
                return ResourceManager.GetString("AllOfTheStudentsGotTheirPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all the other students were registered..
        /// </summary>
        public static string AllTheOtherStudentsWereRegistered {
            get {
                return ResourceManager.GetString("AllTheOtherStudentsWereRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Question History.
        /// </summary>
        public static string AmericanHistory {
            get {
                return ResourceManager.GetString("AmericanHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Choice Question.
        /// </summary>
        public static string AmericanQuestion {
            get {
                return ResourceManager.GetString("AmericanQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous Answers?.
        /// </summary>
        public static string AnonymousAnswers {
            get {
                return ResourceManager.GetString("AnonymousAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Required.
        /// </summary>
        public static string AnswerRequired {
            get {
                return ResourceManager.GetString("AnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to fill all 4 answers.
        /// </summary>
        public static string AnswerStringRequired {
            get {
                return ResourceManager.GetString("AnswerStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer was submitted successfuly.
        /// </summary>
        public static string AnswerSubmitted {
            get {
                return ResourceManager.GetString("AnswerSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string ClickHereToLogIn {
            get {
                return ResourceManager.GetString("ClickHereToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborative Graph.
        /// </summary>
        public static string CollaborativeGraph {
            get {
                return ResourceManager.GetString("CollaborativeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Required.
        /// </summary>
        public static string CommandRequired {
            get {
                return ResourceManager.GetString("CommandRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Answer Required.
        /// </summary>
        public static string correctAnswerStringRequired {
            get {
                return ResourceManager.GetString("correctAnswerStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Activity.
        /// </summary>
        public static string CreateActivity {
            get {
                return ResourceManager.GetString("CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Multiple Choice Question.
        /// </summary>
        public static string CreateAmericanQuestion {
            get {
                return ResourceManager.GetString("CreateAmericanQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Experiment.
        /// </summary>
        public static string CreateExperiment {
            get {
                return ResourceManager.GetString("CreateExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create measurements set.
        /// </summary>
        public static string CreateMeasurementSet {
            get {
                return ResourceManager.GetString("CreateMeasurementSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Question.
        /// </summary>
        public static string CreateQuestion {
            get {
                return ResourceManager.GetString("CreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Short Answer Question.
        /// </summary>
        public static string CreateShortAnswerQuestion {
            get {
                return ResourceManager.GetString("CreateShortAnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create True/False Question.
        /// </summary>
        public static string CreateTrueFalseQuestion {
            get {
                return ResourceManager.GetString("CreateTrueFalseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete measure.
        /// </summary>
        public static string DeleteMeasure {
            get {
                return ResourceManager.GetString("DeleteMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete parameter to measure.
        /// </summary>
        public static string DeleteParameterToMeasure {
            get {
                return ResourceManager.GetString("DeleteParameterToMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string emailConfirmation {
            get {
                return ResourceManager.GetString("emailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the correct answer.
        /// </summary>
        public static string EnterTheCorrectAnswer {
            get {
                return ResourceManager.GetString("EnterTheCorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the image URL:.
        /// </summary>
        public static string EnterTheImageURL {
            get {
                return ResourceManager.GetString("EnterTheImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the instruction:.
        /// </summary>
        public static string EnterTheInstruction {
            get {
                return ResourceManager.GetString("EnterTheInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the activity.
        /// </summary>
        public static string EnterTheNameOfTheActivity {
            get {
                return ResourceManager.GetString("EnterTheNameOfTheActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the image:.
        /// </summary>
        public static string EnterTheNameOfTheImage {
            get {
                return ResourceManager.GetString("EnterTheNameOfTheImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the instruction:.
        /// </summary>
        public static string EnterTheNameOfTheInstruction {
            get {
                return ResourceManager.GetString("EnterTheNameOfTheInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the video:.
        /// </summary>
        public static string EnterTheNameOfTheVideo {
            get {
                return ResourceManager.GetString("EnterTheNameOfTheVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title of the image:.
        /// </summary>
        public static string EnterTheTitle {
            get {
                return ResourceManager.GetString("EnterTheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the video URL:.
        /// </summary>
        public static string EnterTheVideoURL {
            get {
                return ResourceManager.GetString("EnterTheVideoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your question.
        /// </summary>
        public static string EnterYourQuestion {
            get {
                return ResourceManager.GetString("EnterYourQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Activities.
        /// </summary>
        public static string ExistingActivities {
            get {
                return ResourceManager.GetString("ExistingActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment.
        /// </summary>
        public static string Experiment {
            get {
                return ResourceManager.GetString("Experiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Graph.
        /// </summary>
        public static string ExperimentGraph {
            get {
                return ResourceManager.GetString("ExperimentGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment History.
        /// </summary>
        public static string ExperimentHistory {
            get {
                return ResourceManager.GetString("ExperimentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Question.
        /// </summary>
        public static string ExperimentQuestion {
            get {
                return ResourceManager.GetString("ExperimentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explaination.
        /// </summary>
        public static string Explaination {
            get {
                return ResourceManager.GetString("Explaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish And Save.
        /// </summary>
        public static string FinishAndSave {
            get {
                return ResourceManager.GetString("FinishAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Answer.
        /// </summary>
        public static string FirstAnswer {
            get {
                return ResourceManager.GetString("FirstAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Answer.
        /// </summary>
        public static string FourthAnswer {
            get {
                return ResourceManager.GetString("FourthAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Creation.
        /// </summary>
        public static string GroupCreation {
            get {
                return ResourceManager.GetString("GroupCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Preferences.
        /// </summary>
        public static string GroupPreferences {
            get {
                return ResourceManager.GetString("GroupPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Answers.
        /// </summary>
        public static string HideAnswers {
            get {
                return ResourceManager.GetString("HideAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Explanation.
        /// </summary>
        public static string HideExplanation {
            get {
                return ResourceManager.GetString("HideExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History By Activity.
        /// </summary>
        public static string HistoryByActivity {
            get {
                return ResourceManager.GetString("HistoryByActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History By Student.
        /// </summary>
        public static string HistoryByStudent {
            get {
                return ResourceManager.GetString("HistoryByStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting history of an activity will result in deleting this activity histoy from all students.
        /// </summary>
        public static string HistoryDeleteAlert {
            get {
                return ResourceManager.GetString("HistoryDeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History For The Activity.
        /// </summary>
        public static string HistoryForTheActivity {
            get {
                return ResourceManager.GetString("HistoryForTheActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Not Found.
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password/email are incorrect.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login .
        /// </summary>
        public static string LoginInvalid {
            get {
                return ResourceManager.GetString("LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Student Per Group Required.
        /// </summary>
        public static string MaxStudentPerGroupRequired {
            get {
                return ResourceManager.GetString("MaxStudentPerGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Students Per Group.
        /// </summary>
        public static string MaxStudentsPerGroup {
            get {
                return ResourceManager.GetString("MaxStudentsPerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements Set.
        /// </summary>
        public static string MeasurementsSet {
            get {
                return ResourceManager.GetString("MeasurementsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Groups.
        /// </summary>
        public static string NumberOfGroups {
            get {
                return ResourceManager.GetString("NumberOfGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Groups Required.
        /// </summary>
        public static string NumberOfGroupsRequired {
            get {
                return ResourceManager.GetString("NumberOfGroupsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open New Group.
        /// </summary>
        public static string OpenNewGroup {
            get {
                return ResourceManager.GetString("OpenNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters long.
        /// </summary>
        public static string PasswordMustBeAtLeast6 {
            get {
                return ResourceManager.GetString("PasswordMustBeAtLeast6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose number of measurements in set.
        /// </summary>
        public static string PleaseChooseNumberOfMeasurementsInSet {
            get {
                return ResourceManager.GetString("PleaseChooseNumberOfMeasurementsInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose number of parameters to measure.
        /// </summary>
        public static string PleaseChooseNumberOfParametersToMeasure {
            get {
                return ResourceManager.GetString("PleaseChooseNumberOfParametersToMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the step you want to add.
        /// </summary>
        public static string PleaseChooseTheStepYouWantToAdd {
            get {
                return ResourceManager.GetString("PleaseChooseTheStepYouWantToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the time (in seconds) between each two measurements.
        /// </summary>
        public static string PleaseChooseTheTimeBetweenEachTwoMeasurements {
            get {
                return ResourceManager.GetString("PleaseChooseTheTimeBetweenEachTwoMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose time (in seconds) to enter measurement .
        /// </summary>
        public static string PleaseChooseTimeToEnterMeasureInSeconds {
            get {
                return ResourceManager.GetString("PleaseChooseTimeToEnterMeasureInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Graph.
        /// </summary>
        public static string ProgressGraph {
            get {
                return ResourceManager.GetString("ProgressGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Explorer.
        /// </summary>
        public static string projectName {
            get {
                return ResourceManager.GetString("projectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Required.
        /// </summary>
        public static string questionStringRequired {
            get {
                return ResourceManager.GetString("questionStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as new user.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Student.
        /// </summary>
        public static string RegisterStudent {
            get {
                return ResourceManager.GetString("RegisterStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number.
        /// </summary>
        public static string RoomNumber {
            get {
                return ResourceManager.GetString("RoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Answer.
        /// </summary>
        public static string SecondAnswer {
            get {
                return ResourceManager.GetString("SecondAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set As Active.
        /// </summary>
        public static string SetAsActive {
            get {
                return ResourceManager.GetString("SetAsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Answer Question.
        /// </summary>
        public static string ShortAnswerQuestion {
            get {
                return ResourceManager.GetString("ShortAnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Answer Question History.
        /// </summary>
        public static string ShortHistory {
            get {
                return ResourceManager.GetString("ShortHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Participated Activities.
        /// </summary>
        public static string ShowActivities {
            get {
                return ResourceManager.GetString("ShowActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Activity Log.
        /// </summary>
        public static string ShowActivityLog {
            get {
                return ResourceManager.GetString("ShowActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Answers.
        /// </summary>
        public static string ShowAnswers {
            get {
                return ResourceManager.GetString("ShowAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Collaborative Graph.
        /// </summary>
        public static string ShowCollaborativeGraph {
            get {
                return ResourceManager.GetString("ShowCollaborativeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Explanation.
        /// </summary>
        public static string ShowExplanation {
            get {
                return ResourceManager.GetString("ShowExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Groups.
        /// </summary>
        public static string ShowNoAvailableGroups {
            get {
                return ResourceManager.GetString("ShowNoAvailableGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Progress Graph.
        /// </summary>
        public static string ShowProgressGraph {
            get {
                return ResourceManager.GetString("ShowProgressGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student answer was:.
        /// </summary>
        public static string StudentAnswer {
            get {
                return ResourceManager.GetString("StudentAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the students doesn&apos;t register in the system.
        /// </summary>
        public static string StudentErrorMsg1 {
            get {
                return ResourceManager.GetString("StudentErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the students is already registered in a different group.
        /// </summary>
        public static string StudentErrorMsg2 {
            get {
                return ResourceManager.GetString("StudentErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Login.
        /// </summary>
        public static string StudentLogin {
            get {
                return ResourceManager.GetString("StudentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students registered successfully.
        /// </summary>
        public static string StudentsRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("StudentsRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Login.
        /// </summary>
        public static string TeacherLogin {
            get {
                return ResourceManager.GetString("TeacherLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Register.
        /// </summary>
        public static string TeacherRegister {
            get {
                return ResourceManager.GetString("TeacherRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True/False Question History.
        /// </summary>
        public static string TFQHistory {
            get {
                return ResourceManager.GetString("TFQHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activities history have been deleted successfully for student: .
        /// </summary>
        public static string TheActivitiesHistoryHaveBeenDeletedSuccessfullyForStudent {
            get {
                return ResourceManager.GetString("TheActivitiesHistoryHaveBeenDeletedSuccessfullyForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity have been deleted successfully:.
        /// </summary>
        public static string TheActivityHaveBeenDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TheActivityHaveBeenDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity history have been deleted successfully for activity: .
        /// </summary>
        public static string TheActivityHistoryHaveBeenDeletedSuccessfullyForActivity {
            get {
                return ResourceManager.GetString("TheActivityHistoryHaveBeenDeletedSuccessfullyForActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct answer was:.
        /// </summary>
        public static string TheCorrectAnswer {
            get {
                return ResourceManager.GetString("TheCorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation:.
        /// </summary>
        public static string TheExplanationIs {
            get {
                return ResourceManager.GetString("TheExplanationIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The possible answers:.
        /// </summary>
        public static string ThePossibleAnswers {
            get {
                return ResourceManager.GetString("ThePossibleAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Question:.
        /// </summary>
        public static string TheQuestion {
            get {
                return ResourceManager.GetString("TheQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no activity activated right now.
        /// </summary>
        public static string ThereIsNoActivityActivated {
            get {
                return ResourceManager.GetString("ThereIsNoActivityActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The students of each group:.
        /// </summary>
        public static string TheStudentsOfEachGroupAre {
            get {
                return ResourceManager.GetString("TheStudentsOfEachGroupAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Answer.
        /// </summary>
        public static string ThirdAnswer {
            get {
                return ResourceManager.GetString("ThirdAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those students are already registered: .
        /// </summary>
        public static string ThoseStudentsAreAlreadyRegistered {
            get {
                return ResourceManager.GetString("ThoseStudentsAreAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Required.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True/False Question.
        /// </summary>
        public static string TrueFalseQuestion {
            get {
                return ResourceManager.GetString("TrueFalseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can register number of students with CSV file.
        /// </summary>
        public static string UploadExplanation {
            get {
                return ResourceManager.GetString("UploadExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Required.
        /// </summary>
        public static string URLRequired {
            get {
                return ResourceManager.GetString("URLRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string useAnotherServiceToLogIn {
            get {
                return ResourceManager.GetString("useAnotherServiceToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Not Found.
        /// </summary>
        public static string VideoNotFound {
            get {
                return ResourceManager.GetString("VideoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait screen.
        /// </summary>
        public static string waitScreen {
            get {
                return ResourceManager.GetString("waitScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not open a new group, because you are already in an existing group.
        /// </summary>
        public static string YouAreAlreadyInAGroup {
            get {
                return ResourceManager.GetString("YouAreAlreadyInAGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Answer.
        /// </summary>
        public static string YourAnswer {
            get {
                return ResourceManager.GetString("YourAnswer", resourceCulture);
            }
        }
    }
}
